language: python

python:
  - 3.7

install:
  - pip install importlib-metadata --upgrade-
  - pip install -r ebdjangoTest9/requirements.txt

before_script:
  - python ebdjangoTest9/manage.py migrate

script:
  - black . --check
  - flake8 .
  - coverage run ebdjangoTest9/manage.py test polls 

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-west-2"
  app: "sweapp1"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-956591977180"
  on:
    branch: main